---

- name: Update all packages
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: Install epel-release
  yum:
    name: epel-release
    state: latest
 
- name: Install extra packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - python-pip